# Generated by Django 5.1.5 on 2025-01-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="description",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hobby",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female")], default="m", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hobby_1",
            field=models.CharField(default="e", max_length=1),
        ),
        migrations.AddField(
            model_name="user",
            name="hobby_2",
            field=models.CharField(default="e", max_length=1),
        ),
        migrations.AddField(
            model_name="user",
            name="opp_age",
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name="user",
            name="opp_gender",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female")], default="f", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="personality_1",
            field=models.CharField(default="e", max_length=1),
        ),
        migrations.AddField(
            model_name="user",
            name="personality_2",
            field=models.CharField(default="e", max_length=1),
        ),
        migrations.AddField(
            model_name="user",
            name="purpose",
            field=models.CharField(
                choices=[("f", "Friend"), ("l", "Lover")], default="f", max_length=1
            ),
        ),
    ]
